services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./server:/var/www/html
    environment:
      APP_ENV: local
      APP_KEY: base64:bleep
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8000
      DB_HOST: db
      DB_PORT: 3307
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - '3307:3307'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - '8082:8082'
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
